"""add to store is protected

Revision ID: 02462e974330
Revises: 3edb66558cc2
Create Date: 2024-07-23 10:58:45.957476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02462e974330'
down_revision: Union[str, None] = '3edb66558cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('is_protected', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'is_protected')
    # ### end Alembic commands ###
