"""deleted urls from user

Revision ID: 04081df46c7d
Revises: eed4ddb839e0
Create Date: 2024-07-25 16:57:18.366018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04081df46c7d'
down_revision: Union[str, None] = 'eed4ddb839e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'instagram_url')
    op.drop_column('users', 'facebook_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_url', sa.VARCHAR(length=256), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('instagram_url', sa.VARCHAR(length=256), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('linkedin_url', sa.VARCHAR(length=256), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
