"""to subscription add checked date and user add subscriptions

Revision ID: 14a571f23eda
Revises: 44448a38efea
Create Date: 2024-06-12 14:33:58.298512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a571f23eda'
down_revision: Union[str, None] = '44448a38efea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
