"""deleted billing

Revision ID: 2ff3cfe1008c
Revises: 31ddbddf3039
Create Date: 2024-06-11 13:24:57.045178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ff3cfe1008c'
down_revision: Union[str, None] = '31ddbddf3039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_stripe_id', sa.String(length=128), nullable=False),
    sa.Column('subscription_stripe_item_id', sa.String(length=128), nullable=True),
    sa.Column('customer_stripe_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('billings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('customer_stripe_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subscription_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subscription_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('subscription_item_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='billings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='billings_pkey'),
    sa.UniqueConstraint('uuid', name='billings_uuid_key')
    )
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
