"""to store add phone

Revision ID: 322a82391200
Revises: b0c1691b2c55
Create Date: 2024-04-26 17:39:00.341970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322a82391200'
down_revision: Union[str, None] = 'b0c1691b2c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'phone',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.add_column('stores', sa.Column('phone', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'phone')
    op.alter_column('members', 'phone',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
