"""store_logo

Revision ID: 347875a3a2da
Revises: 50658e049907
Create Date: 2024-05-13 12:53:23.578954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347875a3a2da'
down_revision: Union[str, None] = '50658e049907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('logo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stores', 'files', ['logo_id'], ['id'])
    op.drop_column('stores', 'logo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('logo_url', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_constraint('', 'stores', type_='foreignkey')
    op.drop_column('stores', 'logo_id')
    # ### end Alembic commands ###
