"""booked_dates

Revision ID: 3553894acd3c
Revises: 4d1eb631d8bd
Create Date: 2024-05-07 14:29:34.677052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3553894acd3c'
down_revision: Union[str, None] = '4d1eb631d8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booked_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('files', sa.Column('s3_url', sa.String(length=512), nullable=False))
    op.add_column('files', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('files', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('files', 'url',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.create_unique_constraint(None, 'files', ['name'])
    op.create_unique_constraint(None, 'files', ['s3_url'])
    op.drop_column('files', 'owner_type')
    op.drop_column('files', 'owner_id')
    op.add_column('floor_plans', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'floor_plans', 'files', ['image_id'], ['id'])
    op.add_column('items', sa.Column('airbnb_url', sa.String(length=256), nullable=False))
    op.add_column('items', sa.Column('vrbo_url', sa.String(length=256), nullable=False))
    op.add_column('items', sa.Column('expedia_url', sa.String(length=256), nullable=False))
    op.add_column('items', sa.Column('image_id', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('video_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'files', ['image_id'], ['id'])
    op.create_foreign_key(None, 'items', 'files', ['video_id'], ['id'])
    op.drop_column('items', 'type')
    op.drop_column('items', 'price')
    op.drop_column('items', 'category')
    op.add_column('members', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'members', 'files', ['avatar_id'], ['id'])
    op.drop_column('members', 'avatar_url')
    op.add_column('stores', sa.Column('image_id', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('video_id', sa.Integer(), nullable=True))
    op.drop_constraint('stores_name_key', 'stores', type_='unique')
    op.create_foreign_key(None, 'stores', 'files', ['video_id'], ['id'])
    op.create_foreign_key(None, 'stores', 'files', ['image_id'], ['id'])
    op.drop_column('stores', 'name')
    op.drop_column('stores', 'about_us')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('about_us', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('stores', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.create_unique_constraint('stores_name_key', 'stores', ['name'])
    op.drop_column('stores', 'video_id')
    op.drop_column('stores', 'image_id')
    op.add_column('members', sa.Column('avatar_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'avatar_id')
    op.add_column('items', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'video_id')
    op.drop_column('items', 'image_id')
    op.drop_column('items', 'expedia_url')
    op.drop_column('items', 'vrbo_url')
    op.drop_column('items', 'airbnb_url')
    op.drop_constraint(None, 'floor_plans', type_='foreignkey')
    op.drop_column('floor_plans', 'image_id')
    op.add_column('files', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('owner_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_constraint(None, 'files', type_='unique')
    op.alter_column('files', 'url',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('files', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('files', 'is_deleted')
    op.drop_column('files', 's3_url')
    op.drop_table('booked_dates')
    # ### end Alembic commands ###
