"""modify product

Revision ID: 37e7beb1d943
Revises: 41cf0cafd528
Create Date: 2024-06-25 14:10:50.360637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e7beb1d943'
down_revision: Union[str, None] = '41cf0cafd528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'max_active_items')
    op.drop_column('products', 'max_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('max_items', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('max_active_items', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
