"""to subscription add amount

Revision ID: 3edb66558cc2
Revises: 8d00cef0f633
Create Date: 2024-07-10 12:17:32.466806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edb66558cc2'
down_revision: Union[str, None] = '8d00cef0f633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('amount', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'amount')
    # ### end Alembic commands ###
