"""add to product count of items and delete points

Revision ID: 41cf0cafd528
Revises: 78511b1d8cd0
Create Date: 2024-06-24 15:18:17.973071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41cf0cafd528'
down_revision: Union[str, None] = '78511b1d8cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('max_items', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('max_active_items', sa.Integer(), nullable=False))
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('products', 'max_active_items')
    op.drop_column('products', 'max_items')
    # ### end Alembic commands ###
