"""item_adults

Revision ID: 434f8af73a20
Revises: 3add4a4731f8
Create Date: 2024-05-10 14:37:33.957880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434f8af73a20'
down_revision: Union[str, None] = '3add4a4731f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('adults', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'adults')
    # ### end Alembic commands ###
