"""add to user avatar

Revision ID: 4c9f6b97606a
Revises: da645a1270f2
Create Date: 2024-06-03 10:10:33.411365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c9f6b97606a'
down_revision: Union[str, None] = 'da645a1270f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'files', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('', 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_id')
    # ### end Alembic commands ###
