"""to subscription cancel at

Revision ID: 4fe32f882afb
Revises: 392319adca4a
Create Date: 2024-06-12 20:04:23.109736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe32f882afb'
down_revision: Union[str, None] = '392319adca4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_delete')
    op.add_column('subscriptions', sa.Column('canceled_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('last_checked_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'last_checked_date')
    op.drop_column('subscriptions', 'canceled_at')
    op.add_column('products', sa.Column('is_delete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
