"""item_fields_visibility

Revision ID: 5055ede82366
Revises: 394dd6f45ab3
Create Date: 2024-05-16 16:02:19.139299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5055ede82366'
down_revision: Union[str, None] = '394dd6f45ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('show_rates', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('items', sa.Column('show_fees', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('items', sa.Column('show_external_urls', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('items', sa.Column('nightly', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('items', sa.Column('monthly', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('items', sa.Column('annual', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('rates', sa.Column('visible', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rates', 'visible')
    op.drop_column('items', 'annual')
    op.drop_column('items', 'monthly')
    op.drop_column('items', 'nightly')
    op.drop_column('items', 'show_external_urls')
    op.drop_column('items', 'show_fees')
    op.drop_column('items', 'show_rates')
    # ### end Alembic commands ###
