"""add to user subscription item id

Revision ID: 567f5fd0785d
Revises: 8210d52a7f71
Create Date: 2024-05-31 02:27:49.596793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567f5fd0785d'
down_revision: Union[str, None] = '8210d52a7f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('subscription_item_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billings', 'subscription_item_id')
    # ### end Alembic commands ###
