"""add product is deleted

Revision ID: 66316ab3a077
Revises: 6ad7d35ad259
Create Date: 2024-06-11 17:44:20.430366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66316ab3a077'
down_revision: Union[str, None] = '6ad7d35ad259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_delete')
    # ### end Alembic commands ###
