"""add urls

Revision ID: 6c01b13461c9
Revises: 3edb66558cc2
Create Date: 2024-07-25 13:12:52.256075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c01b13461c9'
down_revision: Union[str, None] = '3edb66558cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_contact_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('stores', sa.Column('is_protected', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('instagram_url', sa.String(length=256), server_default='', nullable=False))
    op.add_column('users', sa.Column('messenger_url', sa.String(length=256), server_default='', nullable=False))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=256), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'messenger_url')
    op.drop_column('users', 'instagram_url')
    op.drop_column('stores', 'is_protected')
    op.drop_table('admin_contact_requests')
    # ### end Alembic commands ###
