"""main_media

Revision ID: 772429eef364
Revises: 0552439ca80f
Create Date: 2024-05-15 08:12:17.167132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772429eef364'
down_revision: Union[str, None] = '0552439ca80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('main_media_id', sa.Integer(), nullable=True))
    op.drop_constraint('items_image_id_fkey', 'items', type_='foreignkey')
    op.drop_constraint('items_video_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'files', ['main_media_id'], ['id'])
    op.drop_column('items', 'image_id')
    op.drop_column('items', 'video_id')
    op.add_column('stores', sa.Column('main_media_id', sa.Integer(), nullable=True))
    op.drop_constraint('stores_image_id_fkey', 'stores', type_='foreignkey')
    op.drop_constraint('stores_video_id_fkey', 'stores', type_='foreignkey')
    op.create_foreign_key(None, 'stores', 'files', ['main_media_id'], ['id'])
    op.drop_column('stores', 'image_id')
    op.drop_column('stores', 'video_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.create_foreign_key('stores_video_id_fkey', 'stores', 'files', ['video_id'], ['id'])
    op.create_foreign_key('stores_image_id_fkey', 'stores', 'files', ['image_id'], ['id'])
    op.drop_column('stores', 'main_media_id')
    op.add_column('items', sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_video_id_fkey', 'items', 'files', ['video_id'], ['id'])
    op.create_foreign_key('items_image_id_fkey', 'items', 'files', ['image_id'], ['id'])
    op.drop_column('items', 'main_media_id')
    # ### end Alembic commands ###
