"""add to user subscription

Revision ID: 8210d52a7f71
Revises: e9eca9d9f9f6
Create Date: 2024-05-31 01:24:44.278354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8210d52a7f71'
down_revision: Union[str, None] = 'e9eca9d9f9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
    op.add_column('billings', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    op.add_column('billings', sa.Column('subscription_status', sa.String(length=32), nullable=True))
    op.drop_column('billings', 'subscription_interval')
    op.drop_column('billings', 'subscription_quantity')
    op.drop_column('billings', 'subscription_interval_count')
    op.drop_column('billings', 'payment_method')
    op.drop_column('billings', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('billings', sa.Column('payment_method', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('billings', sa.Column('subscription_interval_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('billings', sa.Column('subscription_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('billings', sa.Column('subscription_interval', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_column('billings', 'subscription_status')
    op.drop_column('billings', 'subscription_end_date')
    op.drop_column('billings', 'subscription_start_date')
    # ### end Alembic commands ###
