"""modify field url in link

Revision ID: 8786fc892da7
Revises: 4fe32f882afb
Create Date: 2024-06-17 14:15:12.917019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8786fc892da7'
down_revision: Union[str, None] = '4fe32f882afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('links_url_key', 'links', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('links_url_key', 'links', ['url'])
    # ### end Alembic commands ###
