"""add created at to contact request

Revision ID: 8d00cef0f633
Revises: ffbee0a15ac6
Create Date: 2024-07-04 12:04:00.372521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d00cef0f633'
down_revision: Union[str, None] = 'ffbee0a15ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_requests', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_requests', 'created_at')
    # ### end Alembic commands ###
