"""add to store about us fields

Revision ID: 9ed5d7dca2a4
Revises: 175bd95f6cb6
Create Date: 2024-05-27 15:41:00.054895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed5d7dca2a4'
down_revision: Union[str, None] = '175bd95f6cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('aboutus_description', sa.Text(), server_default='', nullable=False))
    op.add_column('stores', sa.Column('aboutus_main_media_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stores', 'files', ['aboutus_main_media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("", 'stores', type_='foreignkey')
    op.drop_column('stores', 'aboutus_main_media_id')
    op.drop_column('stores', 'aboutus_description')
    # ### end Alembic commands ###
