"""user - deleted is blocked

Revision ID: a91014e8307f
Revises: 672a01e8e052
Create Date: 2024-06-27 14:43:30.135253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91014e8307f'
down_revision: Union[str, None] = '672a01e8e052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
