"""modify product fields

Revision ID: b2a84b4e7e1a
Revises: 37e7beb1d943
Create Date: 2024-06-25 14:31:04.081969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a84b4e7e1a'
down_revision: Union[str, None] = '37e7beb1d943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('max_items', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('max_active_items', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'max_active_items')
    op.drop_column('products', 'max_items')
    # ### end Alembic commands ###
