"""change password hash

Revision ID: bb5a7aee9cda
Revises: ee334d707c77
Create Date: 2024-06-07 08:21:34.099275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5a7aee9cda'
down_revision: Union[str, None] = 'ee334d707c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('change_password_hash', sa.String(length=256), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'change_password_hash')
    # ### end Alembic commands ###
