"""add to item category, type, count of rooms

Revision ID: cb3a2d0dbd8b
Revises: fbcc13a1dc0f
Create Date: 2024-04-26 11:22:45.060663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3a2d0dbd8b'
down_revision: Union[str, None] = 'fbcc13a1dc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(), nullable=False))
    op.add_column('items', sa.Column('type', sa.String(), nullable=False))
    op.add_column('items', sa.Column('bedrooms_count', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('bathrooms_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'bathrooms_count')
    op.drop_column('items', 'bedrooms_count')
    op.drop_column('items', 'type')
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
