"""add to store about us _aboutus_main_media

Revision ID: d19b7c9e489d
Revises: 9ed5d7dca2a4
Create Date: 2024-05-27 17:57:52.704889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19b7c9e489d'
down_revision: Union[str, None] = '9ed5d7dca2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
