"""to item add city

Revision ID: d93889c6a296
Revises: 322a82391200
Create Date: 2024-04-29 08:43:33.991108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93889c6a296'
down_revision: Union[str, None] = '322a82391200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'items', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("", 'items', type_='foreignkey')
    op.drop_column('items', 'city_id')
    # ### end Alembic commands ###
