"""remove city relationship from item

Revision ID: dd114354945a
Revises: e07d0e088018
Create Date: 2024-07-02 14:13:53.570125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd114354945a'
down_revision: Union[str, None] = 'e07d0e088018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_city_id_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'longitude')
    op.drop_column('items', 'latitude')
    op.drop_column('items', 'city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_foreign_key('items_city_id_fkey', 'items', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###
