"""product add min items an unactive items

Revision ID: e213f6dc8836
Revises: 4749a6ecd8e2
Create Date: 2024-06-30 17:06:38.992359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e213f6dc8836'
down_revision: Union[str, None] = '4749a6ecd8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('min_items', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('unactive_items', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unactive_items')
    op.drop_column('products', 'min_items')
    # ### end Alembic commands ###
