"""add facebook url

Revision ID: e7b573b047a9
Revises: 6c01b13461c9
Create Date: 2024-07-25 13:59:52.785506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b573b047a9'
down_revision: Union[str, None] = '6c01b13461c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_url', sa.String(length=256), server_default='', nullable=False))
    op.drop_column('users', 'messenger_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('messenger_url', sa.VARCHAR(length=256), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_column('users', 'facebook_url')
    # ### end Alembic commands ###
