"""add to user billing

Revision ID: e9eca9d9f9f6
Revises: 2f264434d9f6
Create Date: 2024-05-30 16:57:50.287060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9eca9d9f9f6'
down_revision: Union[str, None] = '2f264434d9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('customer_stripe_id', sa.String(length=128), nullable=True),
    sa.Column('subscription_id', sa.String(length=128), nullable=True),
    sa.Column('subscription_quantity', sa.Integer(), nullable=True),
    sa.Column('subscription_interval', sa.String(length=16), nullable=True),
    sa.Column('subscription_interval_count', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billings')
    # ### end Alembic commands ###
