"""modify fields of billing

Revision ID: ee844b0fa00b
Revises: 90033ac2c240
Create Date: 2024-06-10 12:58:37.481175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee844b0fa00b'
down_revision: Union[str, None] = '90033ac2c240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billings', 'customer_stripe_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('billings', 'subscription_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('billings', 'subscription_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billings', 'subscription_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('billings', 'subscription_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('billings', 'customer_stripe_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
