"""for store change aboutus to about us

Revision ID: ff3a9172be9f
Revises: d19b7c9e489d
Create Date: 2024-05-28 11:02:42.694791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3a9172be9f'
down_revision: Union[str, None] = 'd19b7c9e489d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('about_us_description', sa.Text(), server_default='', nullable=False))
    op.add_column('stores', sa.Column('about_us_main_media_id', sa.Integer(), nullable=True))
    op.drop_constraint('stores_aboutus_main_media_id_fkey', 'stores', type_='foreignkey')
    op.create_foreign_key(None, 'stores', 'files', ['about_us_main_media_id'], ['id'])
    op.drop_column('stores', 'aboutus_main_media_id')
    op.drop_column('stores', 'aboutus_description')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=16), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('stores', sa.Column('aboutus_description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.add_column('stores', sa.Column('aboutus_main_media_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint("", 'stores', type_='foreignkey')
    op.create_foreign_key('stores_aboutus_main_media_id_fkey', 'stores', 'files', ['aboutus_main_media_id'], ['id'])
    op.drop_column('stores', 'about_us_main_media_id')
    op.drop_column('stores', 'about_us_description')
    # ### end Alembic commands ###
