"""remove address field from item

Revision ID: ffbee0a15ac6
Revises: dd114354945a
Create Date: 2024-07-02 17:30:23.627305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbee0a15ac6'
down_revision: Union[str, None] = 'dd114354945a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('address', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
