name: RELEASE

on:
  release:
    types:
      - released

env:
  DOCKER_LOGIN: simple2b
  IMAGE_NAME: simple2b/naples-backend
  DEPLOY_HOST: ${{ secrets.SSH_HOST_IP_PROD }}
  DEPLOY_USER_NAME: ${{ secrets.SSH_USER_PROD }}
  DEPLOY_SSH_KEY: ${{ secrets.SSH_KEY_PROD }}
  DEPLOY_SSH_PORT: ${{ secrets.SSH_PORT_PROD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  on-release:
    runs-on: Linux
    outputs:
      on_develop: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@v1
        id: contains_tag
        with:
          reference: 'develop'
          tag: '${{ github.ref }}'

  deploy:
    name: Deploy
    runs-on: Linux
    needs:
      - on-release
    steps:
      - uses: actions/checkout@v4
      - name: update compose file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER_NAME }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          port: ${{ env.DEPLOY_SSH_PORT }}
          source: docker-compose.prod.yaml
          target: ~/naples/naples-backend
      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER_NAME }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          port: ${{ env.DEPLOY_SSH_PORT }}
          script: |
            cd ~/naples/naples-backend &&
            mv docker-compose.prod.yaml docker-compose.yaml &&
            docker compose pull &&
            docker compose up -d
