# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test backend

on:
  pull_request:
    branches: [main, develop]

env:
  STRIPE_MOCK_URL: http://localhost:12111
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

jobs:
  test:
    name: Test
    runs-on: Linux

    services:
      stripemock:
        image: stripe/stripe-mock:latest
        ports: ['12111:12111']
        options: --name stripemock

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.6.1
      - name: Install dependencies
        working-directory: .
        run: |
          poetry install
      - name: Lint with ruff
        working-directory: .
        run: |
          poetry run ruff check
          poetry run ruff format --check
      - name: Run mypy
        working-directory: .
        run: |
          poetry run mypy
      - name: Run pytest
        working-directory: .
        run: |
          poetry run pytest tests
